name: Android CI/CD with SAST

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      # - name: Run SAST (Static Application Security Testing)
      #   uses: github/codeql-action@v3
      #   with:
      #     languages: android
      #     query: java-code-scanning.qls

      # - name: Upload SAST results
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: .github/codeql-analysis-results.sarif

      - name: Build APK and AAB
        run: |
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v3
        with:
          name: app-bundle
          path: app/build/outputs/bundle/release/app-release.aab
          