name: Android CI/CD with SAST

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
    sast:
        permissions:
          contents: read # for actions/checkout to fetch code
          security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
          actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v3
    
        - name: Setup python
          uses: actions/setup-python@v3
          with:
            python-version: 3.8
    
        - name: Run mobsfscan
          uses: MobSF/mobsfscan@a60d10a83af68e23e0b30611c6515da604f06f65
          with:
            args: . --sarif --output results.sarif || true
    
        - name: Upload mobsfscan report
          uses: github/codeql-action/upload-sarif@v2
          with:
            sarif_file: results.sarif
    
    build:
        needs: sast
        name: Build and Test
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Set up JDK 18
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '18'

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Build with Gradle
          run: ./gradlew build

        # need to change if gradle settings are updated
        - name: Upload APK
          uses: actions/upload-artifact@v3
          with:
            name: app-build
            path: ./app/build/outputs/apk/debug.apk

        # uncomment when gradle settings support aab
        # - name: Upload AAB
        #   uses: actions/upload-artifact@v3
        #   with:
        #     name: app-bundle
        #     path: app/build/outputs/bundle/release/app-release.aab

        # might need to upload to play store maybe
        